name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - docs/**

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  dispatch:

    if: github.repository == 'mikf/gallery-dl'
    runs-on: ubuntu-latest

    steps:
    - name: Dispatch to gdl-org/docs
      run: >
        curl -L
        -X POST
        -H "Accept: application/vnd.github+json"
        -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}"
        -H "X-GitHub-Api-Version: 2022-11-28"
        https://api.github.com/repos/gdl-org/docs/actions/workflows/pages.yml/dispatches
        -d '{"ref":"master"}'

  deploy:

    if: github.repository == 'mikf/gallery-dl'
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: gdl-org/clone@c54f55c32557e4755f08232bdb8a60f94a26fbdd  # v1.0.0

    - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d  # v6.0.0

    - name: Copy static files
      run: |
        mkdir --parents -- ./_site
        cp --archive --target-directory=./_site -- \
          ./docs/oauth-redirect.html

    - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9  # v5.0.0
    - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128  # v5.0.0
      id: deployment
